spring:
  datasource:
    #    url: jdbc:mysql://64.227.146.191:3306/app
    url: jdbc:oracle:thin:@139.59.91.160:1521/ORCLPDB1
    #    username: cdrp
    username: app
    password: app123
    #    password: Cdrp@1234
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      ddl-auto: none
      #      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      dialect: org.hibernate.dialect.Oracle10gDialect
      show-sql: false

jasypt:
  encryptor:
    password: eir
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

notification:
  url: http://159.223.159.153:9509/ceir/addNotifications

alerts:
  postUrl: http://127.0.0.1:9504/eir/alert
  processId: FileCreation
  alerts-mapping:
    DATABASE_EXCEPTION:
      alertId: ALERT2020
    CONFIGURATION_VALUE_MISSING:
      alertId: ALERT2020
    CONFIGURATION_VALUE_WRONG:
      alertId: ALERT2020
    SMS_VALUE_MISSING:
      alertId: ALERT2020
    MODULE_EXECUTED_WITH_EXCEPTION:
      alertId: ALERT2020
    NOTIFICATION_SEND_EXCEPTION:
      alertId: ALERT2020
  process-mapping:
    P4_PROCESS: P4_PROCESS
    PAIRING_EXPIRY_PROCESS: PAIRING_EXPIRY_PROCESS
    GREY_TO_BLACKLIST: GREY_TO_BLACKLIST
    REMINDER_UTILITY: REMINDER_UTILITY
    PAIRING_CLEAN: PAIRING_CLEAN
    PAIR_MGMT_INIT_START_CLEAN: PAIR_MGMT_INIT_START_CLEAN,
    DUPLICATE_EXPIRY_PROCESS: DUPLICATE_EXPIRY_PROCESS
    DUPLICATE_UPDATE_MSISDN: DUPLICATE_UPDATE_MSISDN
    PAIR_UPDATE_MSISDN: PAIR_UPDATE_MSISDN