package com.eirs.blacklist.constant;

public interface QueriesConstants {
    String PARAM_START_RANGE = "<START_RANGE>";
    String IMEI_PATTERN = "<IMEI_PATTERN>";
    String TABLE_NAME = "<TABLE_NAME>";
    String PARAM_END_RANGE = "<END_RANGE>";
    String CDR_TABLE_UNIQUE_IMEI = "app.active_unique_imei";

    String CDR_TABLE_UNIQUE_MSISDN = "app.active_imei_with_different_msisdn";

    String EDR_TABLE_UNIQUE_IMEI = "app_edr.active_unique_imei";

    String EDR_TABLE_UNIQUE_IMSI = "app_edr.active_imei_with_different_imsi";


    String APP_ACTIVE_UNIQUE_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMEI_IMSI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL";
    String APP_ACTIVE_UNIQUE_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMEI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMEI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and B.msisdn is NULL";
    String APP_ACTIVE_UNIQUE_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMSI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'IMSI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and B.msisdn is NULL";
    String APP_ACTIVE_UNIQUE_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORK_CDR',B.imsi,'MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi is NULL and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_TAC = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , '' ,E.actual_imei,E.imei,E.msisdn,B.tac,E.update_filename,'NETWORK_CDR',E.imsi,'IMEI_IMSI_MSISDN',B.created_on, E.modified_on FROM app.blocked_tac_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";

    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    String APP_EDR_ACTIVE_UNIQUE_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMEI_IMSI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL";
    String APP_EDR_ACTIVE_UNIQUE_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMEI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMEI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and B.msisdn is NULL";
    String APP_EDR_ACTIVE_UNIQUE_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMSI_MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'IMSI',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and B.msisdn is NULL";
    String APP_EDR_ACTIVE_UNIQUE_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_EDR',B.imsi,'MSISDN',B.created_on, E.modified_on FROM app.black_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and (B.imei is NULL or B.imei = '" + IMEI_PATTERN + "' ) and B.imsi is NULL and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_TAC = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date, black_list_entry_usage_date) SELECT B.source , '' ,E.actual_imei,E.imei,E.msisdn,B.tac,E.update_filename,'EIR_EDR',E.imsi,'IMEI_IMSI_MSISDN',B.created_on, E.modified_on FROM app.blocked_tac_list B INNER JOIN " + TABLE_NAME + " E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";

    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    String DELETE_WHITE_LIST_RECORDS_IMEI_IMSI_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String DELETE_WHITE_LIST_RECORDS_IMEI_IMSI = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi=E.imsi and E.msisdn is NULL";
    String DELETE_WHITE_LIST_RECORDS_IMEI_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and E.imsi is NULL and B.msisdn=E.msisdn";
    String DELETE_WHITE_LIST_RECORDS_IMEI = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and E.imsi is NULL and E.msisdn is NULL";
    String DELETE_WHITE_LIST_RECORDS_IMSI_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  (E.imei is NULL or E.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String DELETE_WHITE_LIST_RECORDS_IMSI = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  (E.imei is NULL or E.imei = '" + IMEI_PATTERN + "' ) and B.imsi=E.imsi and E.msisdn is NULL";
    String DELETE_WHITE_LIST_RECORDS_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  (E.imei is NULL or E.imei = '" + IMEI_PATTERN + "' ) and E.imsi is NULL and B.msisdn=E.msisdn";
}
