package com.eirs.blacklist.constant;

public interface QueriesConstants {
    String PARAM_START_RANGE = "<START_RANGE>";

    String PARAM_END_RANGE = "<END_RANGE>";

    String APP_ACTIVE_UNIQUE_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_IMSI',B.created_on FROM app.black_list B INNER JOIN app.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL and E.msisdn is NULL";
    String APP_ACTIVE_UNIQUE_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn=E.msisdn";
    String APP_ACTIVE_UNIQUE_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI',B.created_on FROM app.black_list B INNER JOIN app.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn is NULL and E.msisdn is NULL";
    String APP_ACTIVE_UNIQUE_TAC = "insert into aud.black_identify_aud (source,tac,file_name,input_source,blocked_source,blocked_date) SELECT B.source , B.tac,E.update_filename,'NETWORD_EDR','TAC',B.created_on FROM app.blocked_tac_list B INNER JOIN app.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";

    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    String APP_ACTIVE_IMEI_DIFF_MSISDN_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app.active_imei_with_different_msisdn E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_ACTIVE_IMEI_DIFF_MSISDN_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_IMSI',B.created_on FROM app.black_list B INNER JOIN app.active_imei_with_different_msisdn E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL and E.msisdn is NULL";
    String APP_ACTIVE_IMEI_DIFF_MSISDN_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app.active_imei_with_different_msisdn E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn=E.msisdn";
    String APP_ACTIVE_IMEI_DIFF_MSISDN_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'NETWORD_EDR',B.imsi,'IMEI',B.created_on FROM app.black_list B INNER JOIN app.active_imei_with_different_msisdn E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn is NULL and E.msisdn is NULL";
    String APP_ACTIVE_IMEI_DIFF_MSISDN_TAC = "insert into aud.black_identify_aud (source,tac,file_name,input_source,blocked_source,blocked_date) SELECT B.source , B.tac,E.update_filename,'NETWORD_EDR','TAC',B.created_on FROM app.blocked_tac_list B INNER JOIN app.active_imei_with_different_msisdn E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";
    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    String APP_EDR_ACTIVE_UNIQUE_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app_edr.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_IMSI',B.created_on FROM app.black_list B INNER JOIN app_edr.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL and E.msisdn is NULL";
    String APP_EDR_ACTIVE_UNIQUE_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app_edr.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_UNIQUE_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI',B.created_on FROM app.black_list B INNER JOIN app_edr.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn is NULL and E.msisdn is NULL";
    String APP_EDR_ACTIVE_UNIQUE_TAC = "insert into aud.black_identify_aud (source,tac,file_name,input_source,blocked_source,blocked_date) SELECT B.source , B.tac,E.update_filename,'EIR_CDR','TAC',B.created_on FROM app.blocked_tac_list B INNER JOIN app_edr.active_unique_imei E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";
    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    String APP_EDR_ACTIVE_IMEI_DIFF_MSISDN_IMEI_IMSI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_IMSI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app_edr.active_imei_with_different_imsi E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_IMEI_DIFF_MSISDN_IMEI_IMSI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_IMSI',B.created_on FROM app.black_list B INNER JOIN app_edr.active_imei_with_different_imsi E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL and E.msisdn is NULL";
    String APP_EDR_ACTIVE_IMEI_DIFF_MSISDN_IMEI_MSISDN = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI_MSISDN',B.created_on FROM app.black_list B INNER JOIN app_edr.active_imei_with_different_imsi E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn=E.msisdn";
    String APP_EDR_ACTIVE_IMEI_DIFF_MSISDN_IMEI = "insert into aud.black_identify_aud (source,operator,actual_imei,imei,msisdn,tac,file_name,input_source,imsi,blocked_source,blocked_date) SELECT B.source , B.operator_name ,B.actual_imei,B.imei,B.msisdn,B.tac,E.update_filename,'EIR_CDR',B.imsi,'IMEI',B.created_on FROM app.black_list B INNER JOIN app_edr.active_imei_with_different_imsi E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn is NULL and E.msisdn is NULL";
    String APP_EDR_ACTIVE_IMEI_DIFF_MSISDN_TAC = "insert into aud.black_identify_aud (source,tac,file_name,input_source,blocked_source,blocked_date) SELECT B.source , B.tac,E.update_filename,'EIR_CDR','TAC',B.created_on FROM app.blocked_tac_list B INNER JOIN app_edr.active_imei_with_different_imsi E ON E.modified_on >='" + PARAM_START_RANGE + "' and E.modified_on <'" + PARAM_END_RANGE + "' and B.tac=E.tac";
    ////------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    String DELETE_WHITE_LIST_RECORDS_IMEI_IMSI_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi=E.imsi and B.msisdn=E.msisdn";
    String DELETE_WHITE_LIST_RECORDS_IMEI_IMSI = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi=E.imsi and B.msisdn is NULL and E.msisdn is NULL";
    String DELETE_WHITE_LIST_RECORDS_IMEI_MSISDN = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn=E.msisdn";
    String DELETE_WHITE_LIST_RECORDS_IMEI = "delete B from aud.black_identify_aud B INNER JOIN app.exception_list E ON  B.imei=E.imei and B.imsi is NULL and E.imsi is NULL and B.msisdn is NULL and E.msisdn is NULL";
}
